FROM alpine:3.19.0

RUN apk update && apk upgrade && apk add openjdk17-jre-headless

WORKDIR /app

ENV CONFIG=http://config:8888

EXPOSE 80

COPY ./target/api-gateway-0.0.1-SNAPSHOT.jar ./api-gateway.jar

ENTRYPOINT ["java","-jar","/app/api-gateway.jar"]
