pipeline{
    agent{
        label 'jenkins-agent'
    }
    stages{
        stage('mvnw permission'){
            steps{
                sh 'chmod +x mvnw'
            }
        }
        stage('package'){
            steps{
                sh './mvnw clean package -pl api-gateway'
            }
        }
        stage('build'){
            steps{
                sh 'docker build -t gateway ./api-gateway'
            }
        }
        stage('stop container'){
            steps{
                script{
                    def container="gateway"
                    def exists = sh(script: "docker ps --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        sh 'docker stop gateway'
                    }
                }
            }
        }
        stage('remove container'){
            steps{
                script{
                    def container="gateway"
                    def exists = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        sh 'docker rm gateway'
                    }
                }
            }
        }
        stage('start new container'){
            steps{
                sh 'docker run -d -p 80:80 --network RolemanNetwork --name gateway gateway'
            }
        }
    }
    post {
        success {
            discordSend title: "Gateway", description: "Build Success",link: env.BUILD_URL ,result: currentBuild.currentResult, webhookURL: 'https://discord.com/api/webhooks/1187413665746518136/R4NzybodNzGU0aXUxmGbSfRqwD5ZLkKI7xsfHdIjbDBliPmRO9lMFafHqQdP6rzYHatF'
        }
        failure {
            discordSend title: "Gateway", description: "Build Failed", link: env.BUILD_URL ,result: currentBuild.currentResult, webhookURL: 'https://discord.com/api/webhooks/1187413665746518136/R4NzybodNzGU0aXUxmGbSfRqwD5ZLkKI7xsfHdIjbDBliPmRO9lMFafHqQdP6rzYHatF'
        }
        unstable {
            discordSend title: "Gateway", description: "Build Unstable", link: env.BUILD_URL ,result: currentBuild.currentResult, webhookURL: 'https://discord.com/api/webhooks/1187413665746518136/R4NzybodNzGU0aXUxmGbSfRqwD5ZLkKI7xsfHdIjbDBliPmRO9lMFafHqQdP6rzYHatF'
        }
        aborted {
            discordSend title: "Gateway", description: "Build Aborted", link: env.BUILD_URL ,result: currentBuild.currentResult, webhookURL: 'https://discord.com/api/webhooks/1187413665746518136/R4NzybodNzGU0aXUxmGbSfRqwD5ZLkKI7xsfHdIjbDBliPmRO9lMFafHqQdP6rzYHatF'
        }
    }
}