pipeline{
    agent{
        label 'jenkins-agent'
    }
    stages{
        stage('mvnw permission'){
            steps{
                sh 'chmod +x mvnw'
            }
        }
        stage('package'){
            steps{
                sh './mvnw clean package -pl api-gateway'
            }
        }
        stage('build'){
            steps{
                sh 'docker build -t gateway ./api-gateway'
            }
        }
        stage('stop container'){
            steps{
                script{
                    def container="gateway"
                    def exists = sh(script: "docker ps --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        docker stop gateway
                    }
                }
            }
        }
        stage('remove container'){
            steps{
                script{
                    def container="gateway"
                    def exists = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        docker rm gateway
                    }
                }
            }
        }
        stage('start new container'){
            steps{
                sh 'docker run -d -p 80:80 --network RolemanNetwork --name gateway gateway'
            }
        }
    }
}