FROM eclipse-temurin:17-jre-alpine

RUN apk update && apk upgrade

WORKDIR /app

ENV CONFIG=http://config:8888

EXPOSE 8084

COPY ./target/eq-0.0.1-SNAPSHOT.jar ./eq.jar

ENTRYPOINT ["java","-jar","/app/eq.jar"]
