pipeline{
    agent{
        label 'jenkins-agent'
    }
    stages{
        stage('mvnw permission'){
            steps{
                sh 'chmod +x mvnw'
            }
        }
        stage('package'){
            steps{
                sh './mvnw clean package -pl eq'
            }
        }
        stage('build'){
            steps{
                sh 'docker build -t equipment ./eq'
            }
        }
        stage('stop container'){
            steps{
                script{
                     def container="equipment"
                     def exists = sh(script: "docker ps --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                     if(exists){
                        sh 'docker stop equipment'
                     }
                }
            }
        }
        stage('remove container'){
            steps{
                script{
                    def container="equipment"
                    def exists = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        sh 'docker rm equipment'
                    }
                }
            }
        }
        stage('start new container'){
            steps{
                sh 'docker run -d -p 8084:8084 --network RolemanNetwork --name equipment equipment'
            }
        }
    }
}