FROM eclipse-temurin:17-jre-alpine

RUN apk update && apk upgrade

WORKDIR /app

ENV CONFIG=http://config:8888

EXPOSE 8089

COPY ./target/cal-0.0.1-SNAPSHOT.jar ./cal.jar

ENTRYPOINT ["java","-jar","/app/cal.jar"]
