pipeline{
    agent{
        label 'jenkins-agent'
    }
    stages{
        stage('mvnw permission'){
            steps{
                sh 'chmod +x mvnw'
            }
        }
        stage('package'){
            steps{
                sh './mvnw clean package -pl cal'
            }
        }
        stage('build'){
            steps{
                sh 'docker build -t calendar ./cal'
            }
        }
        stage('stop container'){
            steps{
                script{
                    def container="calendar"
                    def exists = sh(script: "docker ps --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        sh 'docker stop calendar'
                    }
                }
            }
        }
        stage('remove container'){
            steps{
                script{
                    def container="calendar"
                    def exists = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        sh 'docker rm calendar'
                    }
                }
            }
        }
        stage('start new container'){
            steps{
                sh 'docker run -d -p 8089:8089 --network RolemanNetwork --name calendar calendar'
            }
        }
    }
    post {
            success {
                discordSend title: "Calendar", description: "Build Success",link: env.BUILD_URL ,result: currentBuild.currentResult, webhookURL: 'https://discord.com/api/webhooks/1187413665746518136/R4NzybodNzGU0aXUxmGbSfRqwD5ZLkKI7xsfHdIjbDBliPmRO9lMFafHqQdP6rzYHatF'
            }

            failure {
                discordSend title: "Calendar", description: "Build Failed", webhookURL: 'https://discord.com/api/webhooks/1187413665746518136/R4NzybodNzGU0aXUxmGbSfRqwD5ZLkKI7xsfHdIjbDBliPmRO9lMFafHqQdP6rzYHatF'
            }

            unstable {
                discordSend title: "Calendar", description: "Build Unstable", webhookURL: 'https://discord.com/api/webhooks/1187413665746518136/R4NzybodNzGU0aXUxmGbSfRqwD5ZLkKI7xsfHdIjbDBliPmRO9lMFafHqQdP6rzYHatF'
            }

            aborted {
                discordSend title: "Calendar", description: "Build Aborted", webhookURL: 'https://discord.com/api/webhooks/1187413665746518136/R4NzybodNzGU0aXUxmGbSfRqwD5ZLkKI7xsfHdIjbDBliPmRO9lMFafHqQdP6rzYHatF'
            }
        }
}