pipeline{
    agent{
        label 'jenkins-agent'
    }
    stages{
        stage('mvnw permission'){
            steps{
                sh 'chmod +x mvnw'
            }
        }
        stage('package'){
            steps{
                sh './mvnw clean package -pl cal'
            }
        }
        stage('build'){
            steps{
                sh 'docker build -t calendar ./cal'
            }
        }
        stage('stop container'){
            steps{
                script{
                    def container="calendar"
                    def exists = sh(script: "docker ps --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        docker stop calendar
                    }
                }
            }
        }
        stage('remove container'){
            steps{
                script{
                    def container="calendar"
                    def exists = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        docker rm calendar
                    }
                }
            }
        }
        stage('start new container'){
            steps{
                sh 'docker run -d -p 8089:8089 --network RolemanNetwork --name calendar calendar'
            }
        }
    }
}