FROM eclipse-temurin:17-jre-alpine

RUN apk update && apk upgrade

WORKDIR /app

ENV CONFIG=http://config:8888

COPY ./target/api-gateway-0.0.1-SNAPSHOT.jar ./api-gateway.jar

ENTRYPOINT ["java","-jar","/app/api-gateway.jar"]
