FROM eclipse-temurin:17-jre-alpine

RUN apk update && apk upgrade

WORKDIR /app

ENV CONFIG=http://config:8888

EXPOSE 8088

COPY ./target/auth-0.0.1-SNAPSHOT.jar ./auth.jar

ENTRYPOINT ["java","-jar","/app/auth.jar"]
