pipeline{
    agent{
        label 'jenkins-agent'
    }
    stages{
        stage('mvnw permission'){
            steps{
                sh 'chmod +x mvnw'
            }
        }
        stage('package'){
            steps{
                sh './mvnw clean package -pl auth'
            }
        }
        stage('build'){
            steps{
                sh 'docker build -t authorization ./auth'
            }
        }
        stage('stop container'){
            steps{
                script{
                    def container="authorization"
                    def exists = sh(script: "docker ps --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        sh 'docker stop authorization'
                    }
                }
            }
        }
        stage('remove container'){
            steps{
                script{
                    def container="authorization"
                    def exists = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        sh 'docker rm authorization'
                    }
                }
            }
        }
        stage('start new container'){
            steps{
                sh 'docker run -d -p 8088:8088 --network RolemanNetwork --name authorization authorization'
            }
        }
    }
}