FROM eclipse-temurin:17-jre-alpine

RUN apk update && apk upgrade

WORKDIR /app

ENV CONFIG=http://config:8888

COPY ./target/service-discovery-0.0.1-SNAPSHOT.jar ./service-discovery.jar

ENTRYPOINT ["java","-jar","/app/service-discovery.jar"]
