pipeline{
    agent{
        label 'jenkins-agent'
    }
    stages{
        stage('mvnw permission'){
            steps{
                sh 'chmod +x mvnw'
            }
        }
        stage('package'){
            steps{
                sh './mvnw clean package -pl service-discovery'
            }
        }
        stage('build'){
            steps{
                sh 'docker build -t eureka ./service-discovery'
            }
        }
        stage('remove existing container'){
            steps{
                script{
                    def container="eureka"
                    def exists = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        docker rm eureka
                    }
                }
            }
        }
        stage('start new container'){
            steps{
                sh 'docker run -d -p 8761:8761 --name eureka eureka'
            }
        }
    }
}