FROM eclipse-temurin:17-jre-alpine

RUN apk update && apk upgrade

WORKDIR /app

ENV CONFIG=http://config:8888

EXPOSE 8083

COPY ./target/data-0.0.1-SNAPSHOT.jar ./data.jar

ENTRYPOINT ["java","-jar","/app/data.jar"]
