pipeline{
    agent{
        label 'jenkins-agent'
    }
    stages{
        stage('mvnw permission'){
            steps{
                sh 'chmod +x mvnw'
            }
        }
        stage('package'){
            steps{
                sh './mvnw clean package -pl data'
            }
        }
        stage('build'){
            steps{
                sh 'docker build -t data ./data'
            }
        }
        stage('stop container'){
            steps{
                script{
                    def container="data"
                    def exists = sh(script: "docker ps --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        sh 'docker stop data'
                    }
                }
            }
        }
        stage('remove container'){
            steps{
                script{
                    def container="data"
                    def exists = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        sh 'docker rm data'
                    }
                }
            }
        }
        stage('start new container'){
            steps{
                sh 'docker run -d -p 8083:8083 --network RolemanNetwork --name data data'
            }
        }
    }
}