FROM eclipse-temurin:17-jre-alpine

RUN apk update && apk upgrade

WORKDIR /app

ENV CONFIG=http://config:8888

EXPOSE 8086

COPY ./target/mp-0.0.1-SNAPSHOT.jar ./mp.jar

ENTRYPOINT ["java","-jar","/app/mp.jar"]
