pipeline{
    agent{
        label 'jenkins-agent'
    }
    stages{
        stage('mvnw permission'){
            steps{
                sh 'chmod +x mvnw'
            }
        }
        stage('package'){
            steps{
                sh './mvnw clean package -pl mp'
            }
        }
        stage('build'){
            steps{
                sh 'docker build -t map ./mp'
            }
        }
        stage('stop container'){
            steps{
                script{
                    def container="map"
                    def exists = sh(script: "docker ps --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        sh 'docker stop map'
                    }
                }
            }
        }
        stage('remove container'){
            steps{
                script{
                    def container="map"
                    def exists = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        sh 'docker rm map'
                    }
                }
            }
        }
        stage('start new container'){
            steps{
                sh 'docker run -d -p 8086:8086 --network RolemanNetwork --name map map'
            }
        }
    }
}