FROM eclipse-temurin:17-jre-alpine

RUN apk update && apk upgrade

WORKDIR /app

ENV CONFIG=http://config:8888

EXPOSE 8087

COPY ./target/wth-0.0.1-SNAPSHOT.jar ./wth.jar

ENTRYPOINT ["java","-jar","/app/wth.jar"]
