FROM eclipse-temurin:17-jre-alpine

RUN apk update && apk upgrade

WORKDIR /app

ENV CONFIG=http://config:8888

EXPOSE 8082

COPY ./target/cp-0.0.1-SNAPSHOT.jar ./cp.jar

ENTRYPOINT ["java","-jar","/app/cp.jar"]
