pipeline{
    agent{
        label 'jenkins-agent'
    }
    stages{
        stage('mvnw permission'){
            steps{
                sh 'chmod +x mvnw'
            }
        }
        stage('package'){
            steps{
                sh './mvnw clean package -pl cp'
            }
        }
        stage('build'){
            steps{
                sh 'docker build -t campaign ./cp'
            }
        }
        stage('stop container'){
            steps{
                script{
                    def container="campaign"
                    def exists = sh(script: "docker ps --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        docker stop campaign
                    }
                }
            }
        }
        stage('remove container'){
            steps{
                script{
                    def container="campaign"
                    def exists = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${container}", returnStatus: true) == 0
                    if(exists){
                        docker rm campaign
                    }
                }
            }
        }
        stage('start new container'){
            steps{
                sh 'docker run -d -p 8082:8082 --network RolemanNetwork --name campaign campaign'
            }
        }
    }
}